// <auto-generated />
namespace Prestes.Cotacao.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Inserindocompradrores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inserindocompradrores));
        
        string IMigrationMetadata.Id
        {
            get { return "201707060239221_Inserindo compradrores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
